services:
  - type: web
    name: cinebucket-api
    env: node
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: node index.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production

      - key: PORT
        value: 10000

      - key: API_KEY
        sync: false

      - key: API_TOKEN
        sync: false

      - key: DB_HOST
        sync: false

      - key: DB_PORT
        sync: false

      - key: DB_USER
        sync: false

      - key: DB_PASSWORD
        sync: false

      - key: DB_NAME
        sync: false
